# Generated by Django 5.2.2 on 2025-06-12 00:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=10, verbose_name='Monto mínimo de pedido')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('500000'), max_digits=10, verbose_name='Monto para envío gratis')),
                ('min_advance_days', models.PositiveIntegerField(default=2, verbose_name='Días mínimos de anticipación')),
                ('max_advance_days', models.PositiveIntegerField(default=90, verbose_name='Días máximos de anticipación')),
                ('business_name', models.CharField(default='Janay', max_length=100, verbose_name='Nombre del negocio')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('address', models.TextField(verbose_name='Dirección del negocio')),
                ('city', models.CharField(default='Villanueva', max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(default='Casanare', max_length=100, verbose_name='Departamento')),
                ('delivery_start_time', models.TimeField(default='05:00', verbose_name='Hora inicio entregas')),
                ('delivery_end_time', models.TimeField(default='21:00', verbose_name='Hora fin entregas')),
                ('accept_cash', models.BooleanField(default=True, verbose_name='Acepta efectivo')),
                ('accept_transfer', models.BooleanField(default=True, verbose_name='Acepta transferencia')),
                ('accept_card', models.BooleanField(default=True, verbose_name='Acepta tarjeta')),
                ('accept_pse', models.BooleanField(default=False, verbose_name='Acepta PSE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuraciones del negocio',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de pedido')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente confirmación'), ('confirmed', 'Confirmado'), ('preparing', 'En preparación'), ('ready', 'Listo para entrega'), ('in_delivery', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('modification_requested', 'Modificación solicitada')], default='draft', max_length=30, verbose_name='Estado')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Recoger en tienda'), ('delivery', 'Delivery')], max_length=20, verbose_name='Tipo de entrega')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Dirección de entrega')),
                ('delivery_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('delivery_city', models.CharField(default='Villanueva', max_length=100, verbose_name='Ciudad')),
                ('delivery_department', models.CharField(default='Casanare', max_length=100, verbose_name='Departamento')),
                ('delivery_references', models.TextField(blank=True, verbose_name='Referencias de ubicación')),
                ('desired_date', models.DateField(verbose_name='Fecha deseada')),
                ('desired_time', models.TimeField(verbose_name='Hora deseada')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Entrega estimada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid_online', 'Pagado en línea'), ('pay_on_delivery', 'Pagar al entregar'), ('pay_later', 'Pagar después'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado del pago')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('pse', 'PSE'), ('pay_later', 'Pagar después')], max_length=20, verbose_name='Método de pago')),
                ('can_pay_later', models.BooleanField(default=False, verbose_name='Puede pagar después')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instrucciones especiales')),
                ('customizations', models.JSONField(blank=True, default=dict, help_text='Ej: {"sabor": "chocolate", "azucar": "sin azucar", "decoracion": "feliz cumpleanos"}', verbose_name='Personalizaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item del pedido',
                'verbose_name_plural': 'Items del pedido',
            },
        ),
        migrations.CreateModel(
            name='OrderModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_type', models.CharField(max_length=50, verbose_name='Tipo de modificación')),
                ('current_data', models.JSONField(verbose_name='Datos actuales')),
                ('requested_data', models.JSONField(verbose_name='Datos solicitados')),
                ('reason', models.TextField(verbose_name='Razón de la modificación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respuesta del administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitud de modificación',
                'verbose_name_plural': 'Solicitudes de modificación',
                'ordering': ['-created_at'],
            },
        ),
    ]
