# Generated by Django 5.2.2 on 2025-08-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customizations',
        ),
    ]
