# Generated by Django 5.2.2 on 2025-08-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_customizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='special_instructions',
        ),
    ]
