# Generated by Django 5.2.2 on 2025-08-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_special_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='can_pay_later',
        ),
    ]
