# Generated by Django 5.2.2 on 2025-08-14 18:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_can_pay_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), help_text='Precio del envío cuando no califica para envío gratis', max_digits=10, verbose_name='Costo de envío'),
        ),
    ]
