# Generated by Django 5.2.6 on 2025-09-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_businesssettings_delivery_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodificationrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='ordermodificationrequest',
            name='modification_type',
            field=models.CharField(default='general', help_text='Ejemplo: cambio de fecha, cambio de dirección, etc.', max_length=50, verbose_name='Tipo de modificación'),
        ),
    ]
