# Generated by Django 5.2.6 on 2025-09-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_ordermodificationrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='cancellation_time_limit_days',
            field=models.PositiveIntegerField(default=1, help_text='Días antes de la entrega hasta cuando se pueden cancelar pedidos', verbose_name='Tiempo límite para cancelaciones (días)'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='modification_time_limit_hours',
            field=models.PositiveIntegerField(default=4, help_text='Horas antes de la entrega hasta cuando se pueden solicitar modificaciones', verbose_name='Tiempo límite para modificaciones (horas)'),
        ),
    ]
