# Generated by Django 5.2.6 on 2025-09-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_businesssettings_cancellation_time_limit_days_and_more'),
        ('orders', '0008_wompi_integration'),
    ]

    operations = [
    ]
