# Generated by Django 5.2.6 on 2025-09-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_update_payment_methods'),
        ('orders', '0010_alter_order_payment_method'),
    ]

    operations = [
    ]
