# Generated by Django 5.2.6 on 2025-09-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_20250927_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('wompi', 'Wompi')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
