# Generated by Django 5.2.6 on 2025-10-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('pse', 'PSE'), ('wompi', 'Wompi'), ('pay_later', 'Pagar después')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
